# Generated by Django 4.0.6 on 2022-09-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groceries', models.IntegerField(default=0)),
                ('personal', models.IntegerField(default=0)),
                ('housing', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(default=0)),
                ('insurance', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='savings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='actual_expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actual_expense', to='budget_planning.expense'),
        ),
        migrations.AddField(
            model_name='user',
            name='expected_expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expected_expense', to='budget_planning.expense'),
        ),
    ]
