# Generated by Django 4.0.6 on 2022-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_planning', '0002_expense_user_savings_user_total_deposit_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
        migrations.AddField(
            model_name='report',
            name='month',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
